### ISSUE TITLE
Wiki - Динамическая строка. Ошибка считывания

### ISSUE THREAD

**Issue by leeroyka** [StriderAJR/StudentCpp#7]
[В Wiki,  в разделе массивы (Динамическая строка)](https://github.com/StriderAJR/StudentCpp/wiki/%D0%9C%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D1%8B#%D0%94%D0%B8%D0%BD%D0%B0%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B0)

В фун-ции чтения строчки
```C++
char* readString()
{
   char buf[255];
   cin.get(buf, 255);
   char* str = new char[strlen(buf)]; 
   strcpy(str, buf);
   return str;
}
```
Ошибка в `cin.get(buf,255);`
**get** - считает 255 символов в любом случае до конца файла и будет пропускать все переходы строчек.
Что в итоге не даст нормально считывать другие строчки, поэтому нужно заменить на **getline**:
`cin.getline(buf,255);`
Чтобы было адекватное "чтение строк"

**Comment by StriderAJR** [comment]
Лучше поздно чем никогда. Исправлено.
